import type { Customer } from "./types";

// Helper function to generate dates
const daysAgo = (days: number): string => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

const monthsAgo = (months: number): string => {
  const date = new Date();
  date.setMonth(date.getMonth() - months);
  return date.toISOString();
};

// Tier pricing mapping
export const TIER_PRICING = {
  Free: 0,
  Startup: 29,
  Growth: 55,
  Scale: 119,
  Enterprise: 319,
};

export const mockCustomers: Customer[] = [
  // REAL MOLIN AI CUSTOMERS
  {
    customerId: "cust_001",
    companyName: "TOParuk.hu",
    currentTier: "Scale",
    signupDate: monthsAgo(14),
    lastLoginDate: daysAgo(35),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 10,
    conversationTrend: [1020, 1055, 1089],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Sales AI", "Lead Gen"],
    featuresNotUsed: ["Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 8,
    industry: "Ecommerce",
    country: "Hungary",
    lastCSMContactDate: daysAgo(8),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_002",
    companyName: "BioTechUSA",
    currentTier: "Growth",
    signupDate: monthsAgo(10),
    lastLoginDate: daysAgo(40),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 10,
    conversationTrend: [440, 455, 465],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Lead Gen"],
    featuresNotUsed: ["Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 8,
    industry: "Nutrition & Supplements",
    country: "Hungary",
    lastCSMContactDate: daysAgo(15),
    customerSentiment: "negative",
  },
  {
    customerId: "cust_003",
    companyName: "CentrumZoo",
    currentTier: "Scale",
    signupDate: monthsAgo(12),
    lastLoginDate: daysAgo(3),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 920,
    conversationTrend: [880, 900, 920],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 6,
    industry: "Pet Supplies",
    country: "Hungary",
    lastCSMContactDate: daysAgo(12),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_004",
    companyName: "Doteo Shop",
    currentTier: "Startup",
    signupDate: monthsAgo(4),
    lastLoginDate: daysAgo(35),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 28,
    conversationTrend: [85, 58, 28],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 2,
    language: "hu",
    numberOfTeamMembers: 2,
    industry: "Ecommerce",
    country: "Hungary",
    lastCSMContactDate: daysAgo(42),
    customerSentiment: "neutral",
  },
  {
    customerId: "cust_005",
    companyName: "P&S Pipes Ltd.",
    currentTier: "Growth",
    signupDate: monthsAgo(8),
    lastLoginDate: daysAgo(5),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 385,
    conversationTrend: [360, 372, 385],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Lead Gen"],
    featuresNotUsed: ["Sales AI", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 4,
    industry: "Industrial Supplies",
    country: "Hungary",
    lastCSMContactDate: daysAgo(16),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_006",
    companyName: "Vagyaim.hu",
    currentTier: "Growth",
    signupDate: monthsAgo(6),
    lastLoginDate: daysAgo(2),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 442,
    conversationTrend: [410, 428, 442],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 5,
    industry: "Ecommerce",
    country: "Hungary",
    lastCSMContactDate: daysAgo(14),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_007",
    companyName: "Hoppline",
    currentTier: "Scale",
    signupDate: monthsAgo(16),
    lastLoginDate: daysAgo(1),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 1165,
    conversationTrend: [1080, 1122, 1165],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Sales AI", "Lead Gen", "Personalization"],
    featuresNotUsed: ["Ninja"],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 10,
    industry: "Ecommerce",
    country: "Hungary",
    lastCSMContactDate: daysAgo(7),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_008",
    companyName: "Fonaltunder Webshop",
    currentTier: "Startup",
    signupDate: monthsAgo(5),
    lastLoginDate: daysAgo(8),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 78,
    conversationTrend: [72, 75, 78],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 2,
    industry: "Craft Supplies",
    country: "Hungary",
    lastCSMContactDate: daysAgo(22),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_009",
    companyName: "Chefs.hu",
    currentTier: "Growth",
    signupDate: monthsAgo(9),
    lastLoginDate: daysAgo(4),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 356,
    conversationTrend: [340, 348, 356],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 4,
    industry: "Kitchen & Restaurant Supplies",
    country: "Hungary",
    lastCSMContactDate: daysAgo(11),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_010",
    companyName: "sneci.hu",
    currentTier: "Scale",
    signupDate: monthsAgo(11),
    lastLoginDate: daysAgo(2),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 1018,
    conversationTrend: [950, 985, 1018],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Sales AI", "Lead Gen"],
    featuresNotUsed: ["Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 7,
    industry: "Ecommerce",
    country: "Hungary",
    lastCSMContactDate: daysAgo(9),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_011",
    companyName: "S-Sport International Kft.",
    currentTier: "Scale",
    signupDate: monthsAgo(15),
    lastLoginDate: daysAgo(1),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 1142,
    conversationTrend: [1065, 1105, 1142],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Sales AI", "Personalization"],
    featuresNotUsed: ["Lead Gen", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 12,
    industry: "Sports Equipment",
    country: "Hungary",
    lastCSMContactDate: daysAgo(6),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_012",
    companyName: "Printker",
    currentTier: "Growth",
    signupDate: monthsAgo(7),
    lastLoginDate: daysAgo(3),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 398,
    conversationTrend: [375, 387, 398],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Lead Gen"],
    featuresNotUsed: ["Sales AI", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 5,
    industry: "Printing Services",
    country: "Hungary",
    lastCSMContactDate: daysAgo(13),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_013",
    companyName: "Dermo.hu",
    currentTier: "Growth",
    signupDate: monthsAgo(8),
    lastLoginDate: daysAgo(2),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 425,
    conversationTrend: [395, 410, 425],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 6,
    industry: "Skincare & Cosmetics",
    country: "Hungary",
    lastCSMContactDate: daysAgo(10),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_014",
    companyName: "Coolmobile",
    currentTier: "Growth",
    signupDate: monthsAgo(6),
    lastLoginDate: daysAgo(28),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 185,
    conversationTrend: [420, 310, 185],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 3,
    industry: "Mobile Retail",
    country: "Hungary",
    lastCSMContactDate: daysAgo(32),
    customerSentiment: "neutral",
  },
  {
    customerId: "cust_015",
    companyName: "Jateknet Toys Webstore",
    currentTier: "Scale",
    signupDate: monthsAgo(13),
    lastLoginDate: daysAgo(4),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 765,
    conversationTrend: [720, 742, 765],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 6,
    industry: "Toy Retail",
    country: "Hungary",
    lastCSMContactDate: daysAgo(14),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_016",
    companyName: "Jatekshop.eu",
    currentTier: "Scale",
    signupDate: monthsAgo(12),
    lastLoginDate: daysAgo(31),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 450,
    conversationTrend: [1100, 890, 450],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Lead Gen"],
    featuresNotUsed: ["Sales AI", "Personalization", "Ninja"],
    supportTicketsLastMonth: 2,
    language: "hu",
    numberOfTeamMembers: 4,
    industry: "Toy Retail",
    country: "Hungary",
    lastCSMContactDate: daysAgo(28),
    customerSentiment: "neutral",
  },
  {
    customerId: "cust_017",
    companyName: "Klimaman",
    currentTier: "Growth",
    signupDate: monthsAgo(5),
    lastLoginDate: daysAgo(6),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 298,
    conversationTrend: [280, 289, 298],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 3,
    industry: "HVAC & Climate Control",
    country: "Hungary",
    lastCSMContactDate: daysAgo(19),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_018",
    companyName: "MultiKisGep",
    currentTier: "Startup",
    signupDate: monthsAgo(4),
    lastLoginDate: daysAgo(10),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 68,
    conversationTrend: [65, 66, 68],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 2,
    industry: "Small Appliances",
    country: "Hungary",
    lastCSMContactDate: daysAgo(24),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_019",
    companyName: "Abdlbolt.hu",
    currentTier: "Startup",
    signupDate: monthsAgo(3),
    lastLoginDate: daysAgo(15),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 52,
    conversationTrend: [68, 60, 52],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 1,
    industry: "Ecommerce",
    country: "Hungary",
    lastCSMContactDate: daysAgo(28),
    customerSentiment: "neutral",
  },
  {
    customerId: "cust_020",
    companyName: "Tactical Ltd.",
    currentTier: "Growth",
    signupDate: monthsAgo(10),
    lastLoginDate: daysAgo(3),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 412,
    conversationTrend: [385, 398, 412],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI", "Lead Gen"],
    featuresNotUsed: ["Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 6,
    industry: "Tactical & Military Equipment",
    country: "Hungary",
    lastCSMContactDate: daysAgo(12),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_058",
    companyName: "Jatekshop",
    currentTier: "Scale",
    signupDate: monthsAgo(12),
    lastLoginDate: daysAgo(32),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 450,
    conversationTrend: [1100, 890, 450],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Lead Gen"],
    featuresNotUsed: ["Sales AI", "Personalization", "Ninja"],
    supportTicketsLastMonth: 2,
    language: "hu",
    numberOfTeamMembers: 4,
    industry: "Toy Retail",
    country: "Hungary",
    lastCSMContactDate: daysAgo(26),
    customerSentiment: "neutral",
  },
  {
    customerId: "cust_059",
    companyName: "HealthTech Solutions",
    currentTier: "Startup",
    signupDate: monthsAgo(3),
    lastLoginDate: daysAgo(5),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 125,
    conversationTrend: [90, 60, 25],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI"],
    supportTicketsLastMonth: 4,
    language: "en",
    numberOfTeamMembers: 1,
    industry: "Healthcare",
    country: "Romania",
    lastCSMContactDate: daysAgo(50),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_060",
    companyName: "CoolMobile",
    currentTier: "Growth",
    signupDate: monthsAgo(6),
    lastLoginDate: daysAgo(35),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 180,
    conversationTrend: [420, 310, 180],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 3,
    industry: "Mobile Retail",
    country: "Hungary",
    lastCSMContactDate: daysAgo(29),
    customerSentiment: "neutral",
  },

  // EXPANSION OPPORTUNITIES (High usage, ready to upgrade)
  {
    customerId: "cust_061",
    companyName: "BioTechUSA",
    currentTier: "Growth",
    signupDate: monthsAgo(10),
    lastLoginDate: daysAgo(1),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 465,
    conversationTrend: [440, 455, 465],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI", "Lead Gen"],
    featuresNotUsed: ["Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 8,
    industry: "Nutrition & Supplements",
    country: "Hungary",
    lastCSMContactDate: daysAgo(15),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_062",
    companyName: "Decathlon Hungary",
    currentTier: "Scale",
    signupDate: monthsAgo(14),
    lastLoginDate: daysAgo(2),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 1138,
    conversationTrend: [1050, 1100, 1138],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Sales AI", "Lead Gen", "Personalization"],
    featuresNotUsed: ["Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 12,
    industry: "Sports Retail",
    country: "Hungary",
    lastCSMContactDate: daysAgo(10),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_063",
    companyName: "eMAG Romania",
    currentTier: "Scale",
    signupDate: monthsAgo(18),
    lastLoginDate: daysAgo(0),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 1089,
    conversationTrend: [1020, 1055, 1089],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "ro",
    numberOfTeamMembers: 15,
    industry: "Ecommerce Marketplace",
    country: "Romania",
    lastCSMContactDate: daysAgo(8),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_064",
    companyName: "BookDepository CEE",
    currentTier: "Growth",
    signupDate: monthsAgo(7),
    lastLoginDate: daysAgo(3),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 412,
    conversationTrend: [380, 395, 412],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Lead Gen"],
    featuresNotUsed: ["Sales AI", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "en",
    numberOfTeamMembers: 5,
    industry: "Book Retail",
    country: "UK",
    lastCSMContactDate: daysAgo(18),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_065",
    companyName: "Fashion Days",
    currentTier: "Startup",
    signupDate: monthsAgo(4),
    lastLoginDate: daysAgo(1),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 108,
    conversationTrend: [95, 102, 108],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "ro",
    numberOfTeamMembers: 3,
    industry: "Fashion Ecommerce",
    country: "Romania",
    lastCSMContactDate: daysAgo(25),
    customerSentiment: "positive",
  },

  // HEALTHY CUSTOMERS (Good engagement, moderate usage)
  {
    customerId: "cust_066",
    companyName: "Tesco Hungary",
    currentTier: "Enterprise",
    signupDate: monthsAgo(24),
    lastLoginDate: daysAgo(1),
    monthlyConversationLimit: 999999,
    conversationsUsedThisMonth: 4850,
    conversationTrend: [4600, 4720, 4850],
    monthlyRecurringRevenue: 319,
    featuresUsed: ["Support AI", "Sales AI", "Lead Gen", "Personalization", "Ninja"],
    featuresNotUsed: [],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 25,
    industry: "Grocery Retail",
    country: "Hungary",
    lastCSMContactDate: daysAgo(7),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_067",
    companyName: "Alza.cz",
    currentTier: "Enterprise",
    signupDate: monthsAgo(20),
    lastLoginDate: daysAgo(0),
    monthlyConversationLimit: 999999,
    conversationsUsedThisMonth: 6200,
    conversationTrend: [5900, 6050, 6200],
    monthlyRecurringRevenue: 319,
    featuresUsed: ["Support AI", "Sales AI", "Lead Gen", "Personalization"],
    featuresNotUsed: ["Ninja"],
    supportTicketsLastMonth: 1,
    language: "cs",
    numberOfTeamMembers: 30,
    industry: "Electronics Ecommerce",
    country: "Czech Republic",
    lastCSMContactDate: daysAgo(5),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_068",
    companyName: "Notino",
    currentTier: "Scale",
    signupDate: monthsAgo(15),
    lastLoginDate: daysAgo(2),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 780,
    conversationTrend: [720, 750, 780],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Sales AI", "Lead Gen"],
    featuresNotUsed: ["Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "cs",
    numberOfTeamMembers: 10,
    industry: "Beauty & Cosmetics",
    country: "Czech Republic",
    lastCSMContactDate: daysAgo(12),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_069",
    companyName: "Answear.com",
    currentTier: "Growth",
    signupDate: monthsAgo(9),
    lastLoginDate: daysAgo(42),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 20,
    conversationTrend: [290, 305, 320],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "pl",
    numberOfTeamMembers: 7,
    industry: "Fashion Ecommerce",
    country: "Poland",
    lastCSMContactDate: daysAgo(14),
    customerSentiment: "negative",
  },
  {
    customerId: "cust_070",
    companyName: "Glovo Hungary",
    currentTier: "Scale",
    signupDate: monthsAgo(11),
    lastLoginDate: daysAgo(1),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 950,
    conversationTrend: [880, 915, 950],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Lead Gen"],
    featuresNotUsed: ["Sales AI", "Personalization", "Ninja"],
    supportTicketsLastMonth: 2,
    language: "hu",
    numberOfTeamMembers: 8,
    industry: "Food Delivery",
    country: "Hungary",
    lastCSMContactDate: daysAgo(9),
    customerSentiment: "positive",
  },

  // MEDIUM USAGE CUSTOMERS (Potential to grow or risk to decline)
  {
    customerId: "cust_071",
    companyName: "ReserveTable Budapest",
    currentTier: "Startup",
    signupDate: monthsAgo(5),
    lastLoginDate: daysAgo(8),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 65,
    conversationTrend: [70, 68, 65],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 2,
    industry: "Restaurant Tech",
    country: "Hungary",
    lastCSMContactDate: daysAgo(22),
    customerSentiment: "neutral",
  },
  {
    customerId: "cust_072",
    companyName: "HomeDeco.ro",
    currentTier: "Growth",
    signupDate: monthsAgo(8),
    lastLoginDate: daysAgo(5),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 245,
    conversationTrend: [260, 250, 245],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Lead Gen"],
    featuresNotUsed: ["Sales AI", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "ro",
    numberOfTeamMembers: 4,
    industry: "Home Decor",
    country: "Romania",
    lastCSMContactDate: daysAgo(17),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_073",
    companyName: "TechStore Bulgaria",
    currentTier: "Startup",
    signupDate: monthsAgo(3),
    lastLoginDate: daysAgo(6),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 58,
    conversationTrend: [62, 60, 58],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 2,
    language: "bg",
    numberOfTeamMembers: 2,
    industry: "Electronics Retail",
    country: "Bulgaria",
    lastCSMContactDate: daysAgo(28),
    customerSentiment: "neutral",
  },
  {
    customerId: "cust_074",
    companyName: "Pet Paradise",
    currentTier: "Growth",
    signupDate: monthsAgo(7),
    lastLoginDate: daysAgo(3),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 280,
    conversationTrend: [270, 275, 280],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 3,
    industry: "Pet Supplies",
    country: "Hungary",
    lastCSMContactDate: daysAgo(11),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_075",
    companyName: "AutoParts CEE",
    currentTier: "Scale",
    signupDate: monthsAgo(13),
    lastLoginDate: daysAgo(4),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 620,
    conversationTrend: [650, 635, 620],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Lead Gen"],
    featuresNotUsed: ["Sales AI", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "en",
    numberOfTeamMembers: 6,
    industry: "Automotive Parts",
    country: "Slovakia",
    lastCSMContactDate: daysAgo(13),
    customerSentiment: "positive",
  },

  // MORE EXPANSION OPPORTUNITIES
  {
    customerId: "cust_021",
    companyName: "MediaMarkt Hungary",
    currentTier: "Scale",
    signupDate: monthsAgo(16),
    lastLoginDate: daysAgo(1),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 1195,
    conversationTrend: [1120, 1160, 1195],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Sales AI", "Lead Gen"],
    featuresNotUsed: ["Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 18,
    industry: "Electronics Retail",
    country: "Hungary",
    lastCSMContactDate: daysAgo(6),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_022",
    companyName: "Sephora CEE",
    currentTier: "Growth",
    signupDate: monthsAgo(6),
    lastLoginDate: daysAgo(2),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 445,
    conversationTrend: [410, 428, 445],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "en",
    numberOfTeamMembers: 9,
    industry: "Beauty & Cosmetics",
    country: "Poland",
    lastCSMContactDate: daysAgo(16),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_023",
    companyName: "Zara Romania",
    currentTier: "Growth",
    signupDate: monthsAgo(8),
    lastLoginDate: daysAgo(1),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 478,
    conversationTrend: [440, 460, 478],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Lead Gen"],
    featuresNotUsed: ["Sales AI", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "ro",
    numberOfTeamMembers: 11,
    industry: "Fashion Retail",
    country: "Romania",
    lastCSMContactDate: daysAgo(19),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_024",
    companyName: "SportsDirect Poland",
    currentTier: "Startup",
    signupDate: monthsAgo(4),
    lastLoginDate: daysAgo(2),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 115,
    conversationTrend: [105, 110, 115],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "pl",
    numberOfTeamMembers: 4,
    industry: "Sports Retail",
    country: "Poland",
    lastCSMContactDate: daysAgo(21),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_025",
    companyName: "Auchan Hungary",
    currentTier: "Scale",
    signupDate: monthsAgo(19),
    lastLoginDate: daysAgo(0),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 1122,
    conversationTrend: [1050, 1085, 1122],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Sales AI", "Personalization"],
    featuresNotUsed: ["Lead Gen", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 14,
    industry: "Grocery Retail",
    country: "Hungary",
    lastCSMContactDate: daysAgo(8),
    customerSentiment: "positive",
  },

  // MORE AT-RISK CUSTOMERS
  {
    customerId: "cust_026",
    companyName: "TechnoLine Slovakia",
    currentTier: "Startup",
    signupDate: monthsAgo(4),
    lastLoginDate: daysAgo(31),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 38,
    conversationTrend: [85, 62, 38],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 3,
    language: "sk",
    numberOfTeamMembers: 1,
    industry: "Electronics Retail",
    country: "Slovakia",
    lastCSMContactDate: daysAgo(40),
    customerSentiment: "negative",
  },
  {
    customerId: "cust_027",
    companyName: "GardenPro Bulgaria",
    currentTier: "Growth",
    signupDate: monthsAgo(7),
    lastLoginDate: daysAgo(28),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 145,
    conversationTrend: [380, 260, 145],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 2,
    language: "bg",
    numberOfTeamMembers: 3,
    industry: "Garden Supplies",
    country: "Bulgaria",
    lastCSMContactDate: daysAgo(35),
    customerSentiment: "neutral",
  },
  {
    customerId: "cust_028",
    companyName: "WineStore Croatia",
    currentTier: "Startup",
    signupDate: monthsAgo(2),
    lastLoginDate: daysAgo(26),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 42,
    conversationTrend: [68, 55, 42],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hr",
    numberOfTeamMembers: 2,
    industry: "Wine Retail",
    country: "Croatia",
    lastCSMContactDate: daysAgo(30),
    customerSentiment: "neutral",
  },
  {
    customerId: "cust_029",
    companyName: "OfficeSupply Romania",
    currentTier: "Growth",
    signupDate: monthsAgo(9),
    lastLoginDate: daysAgo(34),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 125,
    conversationTrend: [350, 240, 125],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 2,
    language: "ro",
    numberOfTeamMembers: 2,
    industry: "Office Supplies",
    country: "Romania",
    lastCSMContactDate: daysAgo(42),
    customerSentiment: "neutral",
  },
  {
    customerId: "cust_030",
    companyName: "BuildMart Serbia",
    currentTier: "Scale",
    signupDate: monthsAgo(11),
    lastLoginDate: daysAgo(29),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 380,
    conversationTrend: [920, 650, 380],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "sr",
    numberOfTeamMembers: 5,
    industry: "Building Materials",
    country: "Serbia",
    lastCSMContactDate: daysAgo(33),
    customerSentiment: "neutral",
  },

  // DIVERSE MIX OF OTHER CUSTOMERS
  {
    customerId: "cust_031",
    companyName: "PharmaDirect Poland",
    currentTier: "Growth",
    signupDate: monthsAgo(10),
    lastLoginDate: daysAgo(5),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 335,
    conversationTrend: [310, 320, 335],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Lead Gen"],
    featuresNotUsed: ["Sales AI", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "pl",
    numberOfTeamMembers: 6,
    industry: "Pharmacy",
    country: "Poland",
    lastCSMContactDate: daysAgo(15),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_032",
    companyName: "ToyUniverse Czech",
    currentTier: "Startup",
    signupDate: monthsAgo(3),
    lastLoginDate: daysAgo(7),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 72,
    conversationTrend: [68, 70, 72],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "cs",
    numberOfTeamMembers: 2,
    industry: "Toy Retail",
    country: "Czech Republic",
    lastCSMContactDate: daysAgo(20),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_033",
    companyName: "BikeShop Slovenia",
    currentTier: "Growth",
    signupDate: monthsAgo(6),
    lastLoginDate: daysAgo(4),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 298,
    conversationTrend: [280, 289, 298],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "sl",
    numberOfTeamMembers: 4,
    industry: "Bicycle Retail",
    country: "Slovenia",
    lastCSMContactDate: daysAgo(12),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_034",
    companyName: "FurnitureHub Hungary",
    currentTier: "Scale",
    signupDate: monthsAgo(17),
    lastLoginDate: daysAgo(3),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 845,
    conversationTrend: [810, 825, 845],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Sales AI", "Lead Gen"],
    featuresNotUsed: ["Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 9,
    industry: "Furniture Retail",
    country: "Hungary",
    lastCSMContactDate: daysAgo(10),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_035",
    companyName: "TechRepair Bulgaria",
    currentTier: "Startup",
    signupDate: monthsAgo(2),
    lastLoginDate: daysAgo(9),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 55,
    conversationTrend: [60, 58, 55],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 2,
    language: "bg",
    numberOfTeamMembers: 1,
    industry: "Tech Repair Services",
    country: "Bulgaria",
    lastCSMContactDate: daysAgo(25),
    customerSentiment: "neutral",
  },
  {
    customerId: "cust_036",
    companyName: "FoodMarket Romania",
    currentTier: "Growth",
    signupDate: monthsAgo(12),
    lastLoginDate: daysAgo(2),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 410,
    conversationTrend: [390, 400, 410],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Lead Gen"],
    featuresNotUsed: ["Sales AI", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "ro",
    numberOfTeamMembers: 7,
    industry: "Food Retail",
    country: "Romania",
    lastCSMContactDate: daysAgo(11),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_037",
    companyName: "JewelryBox Hungary",
    currentTier: "Startup",
    signupDate: monthsAgo(5),
    lastLoginDate: daysAgo(15),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 48,
    conversationTrend: [75, 62, 48],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 2,
    industry: "Jewelry",
    country: "Hungary",
    lastCSMContactDate: daysAgo(23),
    customerSentiment: "neutral",
  },
  {
    customerId: "cust_038",
    companyName: "ShoePalace Poland",
    currentTier: "Growth",
    signupDate: monthsAgo(8),
    lastLoginDate: daysAgo(3),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 365,
    conversationTrend: [340, 352, 365],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "pl",
    numberOfTeamMembers: 5,
    industry: "Footwear",
    country: "Poland",
    lastCSMContactDate: daysAgo(13),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_039",
    companyName: "CraftBeer Slovakia",
    currentTier: "Startup",
    signupDate: monthsAgo(4),
    lastLoginDate: daysAgo(10),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 62,
    conversationTrend: [65, 64, 62],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "sk",
    numberOfTeamMembers: 2,
    industry: "Beverage",
    country: "Slovakia",
    lastCSMContactDate: daysAgo(18),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_040",
    companyName: "LaptopStore Serbia",
    currentTier: "Growth",
    signupDate: monthsAgo(7),
    lastLoginDate: daysAgo(6),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 272,
    conversationTrend: [280, 276, 272],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "sr",
    numberOfTeamMembers: 3,
    industry: "Computer Retail",
    country: "Serbia",
    lastCSMContactDate: daysAgo(14),
    customerSentiment: "positive",
  },

  // ADDITIONAL EXPANSION OPPORTUNITIES
  {
    customerId: "cust_041",
    companyName: "SmartHome Croatia",
    currentTier: "Startup",
    signupDate: monthsAgo(3),
    lastLoginDate: daysAgo(1),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 118,
    conversationTrend: [108, 113, 118],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "hr",
    numberOfTeamMembers: 3,
    industry: "Smart Home Tech",
    country: "Croatia",
    lastCSMContactDate: daysAgo(24),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_042",
    companyName: "BabyWorld Hungary",
    currentTier: "Growth",
    signupDate: monthsAgo(9),
    lastLoginDate: daysAgo(2),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 458,
    conversationTrend: [425, 442, 458],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 6,
    industry: "Baby Products",
    country: "Hungary",
    lastCSMContactDate: daysAgo(17),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_043",
    companyName: "GamingStore Poland",
    currentTier: "Scale",
    signupDate: monthsAgo(14),
    lastLoginDate: daysAgo(1),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 1065,
    conversationTrend: [980, 1025, 1065],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "pl",
    numberOfTeamMembers: 10,
    industry: "Gaming",
    country: "Poland",
    lastCSMContactDate: daysAgo(9),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_044",
    companyName: "OutdoorGear Slovakia",
    currentTier: "Startup",
    signupDate: monthsAgo(2),
    lastLoginDate: daysAgo(3),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 102,
    conversationTrend: [88, 95, 102],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "sk",
    numberOfTeamMembers: 2,
    industry: "Outdoor Equipment",
    country: "Slovakia",
    lastCSMContactDate: daysAgo(19),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_045",
    companyName: "WatchShop Czech",
    currentTier: "Growth",
    signupDate: monthsAgo(11),
    lastLoginDate: daysAgo(4),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 392,
    conversationTrend: [370, 381, 392],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Lead Gen"],
    featuresNotUsed: ["Sales AI", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "cs",
    numberOfTeamMembers: 5,
    industry: "Watches & Accessories",
    country: "Czech Republic",
    lastCSMContactDate: daysAgo(15),
    customerSentiment: "positive",
  },

  // FINAL SET - MIX OF RISK AND OPPORTUNITY
  {
    customerId: "cust_046",
    companyName: "Euronics",
    currentTier: "Enterprise",
    signupDate: monthsAgo(20),
    lastLoginDate: daysAgo(1),
    monthlyConversationLimit: 999999,
    conversationsUsedThisMonth: 3850,
    conversationTrend: [3600, 3720, 3850],
    monthlyRecurringRevenue: 319,
    featuresUsed: ["Support AI", "Sales AI", "Lead Gen", "Personalization"],
    featuresNotUsed: ["Ninja"],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 20,
    industry: "Electronics Retail",
    country: "Hungary",
    lastCSMContactDate: daysAgo(5),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_047",
    companyName: "Desirel",
    currentTier: "Scale",
    signupDate: monthsAgo(11),
    lastLoginDate: daysAgo(2),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 1045,
    conversationTrend: [980, 1012, 1045],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Sales AI", "Lead Gen"],
    featuresNotUsed: ["Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 9,
    industry: "Home & Living",
    country: "Hungary",
    lastCSMContactDate: daysAgo(8),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_048",
    companyName: "Decathlon",
    currentTier: "Enterprise",
    signupDate: monthsAgo(18),
    lastLoginDate: daysAgo(0),
    monthlyConversationLimit: 999999,
    conversationsUsedThisMonth: 5200,
    conversationTrend: [4900, 5050, 5200],
    monthlyRecurringRevenue: 319,
    featuresUsed: ["Support AI", "Sales AI", "Lead Gen", "Personalization", "Ninja"],
    featuresNotUsed: [],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 25,
    industry: "Sports Retail",
    country: "Hungary",
    lastCSMContactDate: daysAgo(4),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_049",
    companyName: "Homelux",
    currentTier: "Growth",
    signupDate: monthsAgo(7),
    lastLoginDate: daysAgo(3),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 402,
    conversationTrend: [380, 391, 402],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 5,
    industry: "Home Decor",
    country: "Hungary",
    lastCSMContactDate: daysAgo(11),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_050",
    companyName: "Insportline",
    currentTier: "Scale",
    signupDate: monthsAgo(14),
    lastLoginDate: daysAgo(1),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 1098,
    conversationTrend: [1020, 1060, 1098],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Sales AI", "Personalization"],
    featuresNotUsed: ["Lead Gen", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 11,
    industry: "Sports Equipment",
    country: "Hungary",
    lastCSMContactDate: daysAgo(6),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_051",
    companyName: "Lumenet",
    currentTier: "Growth",
    signupDate: monthsAgo(8),
    lastLoginDate: daysAgo(2),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 435,
    conversationTrend: [405, 420, 435],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI", "Lead Gen"],
    featuresNotUsed: ["Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "hu",
    numberOfTeamMembers: 6,
    industry: "Lighting & Electrical",
    country: "Hungary",
    lastCSMContactDate: daysAgo(9),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_052",
    companyName: "Veloforte",
    currentTier: "Startup",
    signupDate: monthsAgo(5),
    lastLoginDate: daysAgo(4),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 95,
    conversationTrend: [88, 92, 95],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "en",
    numberOfTeamMembers: 3,
    industry: "Sports Nutrition",
    country: "UK",
    lastCSMContactDate: daysAgo(18),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_053",
    companyName: "Goose Creek",
    currentTier: "Growth",
    signupDate: monthsAgo(9),
    lastLoginDate: daysAgo(3),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 378,
    conversationTrend: [355, 366, 378],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "en",
    numberOfTeamMembers: 5,
    industry: "Home Fragrance",
    country: "USA",
    lastCSMContactDate: daysAgo(14),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_054",
    companyName: "Benu",
    currentTier: "Scale",
    signupDate: monthsAgo(13),
    lastLoginDate: daysAgo(2),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 892,
    conversationTrend: [850, 870, 892],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 8,
    industry: "Pharmacy",
    country: "Hungary",
    lastCSMContactDate: daysAgo(10),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_055",
    companyName: "Cosori",
    currentTier: "Growth",
    signupDate: monthsAgo(6),
    lastLoginDate: daysAgo(1),
    monthlyConversationLimit: 500,
    conversationsUsedThisMonth: 458,
    conversationTrend: [425, 442, 458],
    monthlyRecurringRevenue: 55,
    featuresUsed: ["Support AI", "Sales AI"],
    featuresNotUsed: ["Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 0,
    language: "en",
    numberOfTeamMembers: 7,
    industry: "Kitchen Appliances",
    country: "USA",
    lastCSMContactDate: daysAgo(12),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_056",
    companyName: "Unfabled",
    currentTier: "Startup",
    signupDate: monthsAgo(4),
    lastLoginDate: daysAgo(5),
    monthlyConversationLimit: 125,
    conversationsUsedThisMonth: 82,
    conversationTrend: [75, 78, 82],
    monthlyRecurringRevenue: 29,
    featuresUsed: ["Support AI"],
    featuresNotUsed: ["Sales AI", "Lead Gen", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "en",
    numberOfTeamMembers: 2,
    industry: "Fashion & Apparel",
    country: "UK",
    lastCSMContactDate: daysAgo(20),
    customerSentiment: "positive",
  },
  {
    customerId: "cust_057",
    companyName: "Medence Óriás",
    currentTier: "Scale",
    signupDate: monthsAgo(10),
    lastLoginDate: daysAgo(3),
    monthlyConversationLimit: 1250,
    conversationsUsedThisMonth: 745,
    conversationTrend: [710, 728, 745],
    monthlyRecurringRevenue: 119,
    featuresUsed: ["Support AI", "Lead Gen"],
    featuresNotUsed: ["Sales AI", "Personalization", "Ninja"],
    supportTicketsLastMonth: 1,
    language: "hu",
    numberOfTeamMembers: 6,
    industry: "Swimming Pools & Equipment",
    country: "Hungary",
    lastCSMContactDate: daysAgo(13),
    customerSentiment: "positive",
  },
];

// Export count for convenience
export const CUSTOMER_COUNT = mockCustomers.length;
